### ISSUE TITLE
[Bug]: Can't read a url with pandas.read_csv()

### ISSUE THREAD

**Issue by juanfcocontreras** [coatless-quarto/pyodide#9] opened 2024-02-29 17:49 UTC
### Bug description

I can't read a file from a url with pandas

### Steps to reproduce

```{pyodide-python}
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
```

```
PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 393, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 3, in 
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 363, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
         ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 265, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: 
```

### Your environment

- IDE: VSCode
- MacOS 14.3.1 (23D60)

### Quarto check output

```
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /opt/homebrew/Caskroom/miniforge/base/bin/python
      Jupyter: 5.7.1
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/user/.local/R_libs
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by coatless** [comment] 2024-03-01 07:02
@juanfcocontreras thanks for raising the issue! I can confirm that this is indeed problematic. Though, the issue here is with the upstream version of `pandas` that is compiled for `pyodide`. For example, if we try your example in the [Pyodide REPL](https://pyodide.org/en/stable/console.html), we end up getting the same outcome: 

<img width="1236" alt="Pandas URL bug" src="https://github.com/coatless-quarto/pyodide/assets/833642/910644c7-0b35-4866-b295-15bee62362b3">

**Comment by coatless** [comment] 2024-03-01 07:33
@juanfcocontreras I filed it upstream at: 

https://github.com/pyodide/pyodide/issues/4585

That said, I can put a patch in that will automatically load [`pyodide-http`](https://github.com/koenvo/pyodide-http), which shims the `urllib` and `requests` library. 

For example, using:

```python
# 1. Install this package
import micropip
await micropip.install('pyodide-http')

# 2. Patch requests
import pyodide_http
pyodide_http.patch_all()  # Patch all libraries

# 3. Run pandas code
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
```

Provides us with a viable data read: 

<img width="1201" alt="Demo of pandas working in browser with `pyodide-http` shim active" src="https://github.com/coatless-quarto/pyodide/assets/833642/20bd661d-02ee-4f3a-ba49-17fe5027fc53">

**Comment by juanfcocontreras** [comment] 2024-03-01 12:11
Hi @coatless ,

Thank you very much for your detailed reply, it's the first time I use `pyodide` (even if indirectly) and I didn't know the problem was there.

I think that temporarily, it may be useful to automatically load `pyodide-http` so that the network part works with several packages in a transparent way for the one using your extension.

In any case thank you very much for your help, because I can now continue to use your extension.

**Comment by coatless** [comment] 2024-03-01 20:14
@juanfcocontreras no worries, thanks for using the extension! Please raise issues as you encounter them. I'll try to mitigate as best as I can.

**Comment by coatless** [comment] 2024-03-01 20:43
Notes to my future self or someone else who stumbles upon this thread:

- The problem is a lack of sockets or TLS APIs for Emscripten/WASI causing the usual `urllib3` behavior to fail when querying URLs.
- The creator of `urllib3` mentioned initial support for Python's WASM backend in `urllib3` version 2 in: https://sethmlarson.dev/urllib3-is-fundraising-for-http2-support#support-for-webassembly-and-emscripten
- The [PR urllib3/urllib3#3195](https://github.com/urllib3/urllib3/pull/3195) with native support landed on Nov 25, 2023 and was part of the [`urllib3` 2.2.0 release](https://github.com/urllib3/urllib3/releases/tag/2.2.0) on Jan 30, 2024.
- This PR uses JS `fetch`/XHR under the hood instead of using `urllib3` to get around the sockets hiccup.
- As it stands, pyodide version 0.25.0 ships with [`urllib3` 2.1.0](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) as part of the default configuration. So, we cannot get the benefits until a later version of `pyodide` is available with an updated base default.
- Our current workaround is then to use [`pyodide-http`](https://github.com/koenvo/pyodide-http), which provides  `pyodide_http.patch_all()` function to patch `requests` and `urllib3` requests.

So, using: 

```python
import pyodide_http
pyodide_http.patch_all()  # Patch all libraries
```

This gives us a nice shim for the time being.

**Closed as completed** 2024-03-02 10:04 UTC
Labels: t: bug, s: confirmed, p: medium, t: upstream

**Comment by coatless** [comment] 2024-03-02 10:05
@juanfcocontreras feel free to grab an updated version of the extension for a fix to the above issue.

```sh
quarto add coatless-quarto/pyodide
```

**Comment by juanfcocontreras** [comment] 2024-03-02 20:02
> @juanfcocontreras feel free to grab an updated version of the extension for a fix to the above issue.
> 
> ```shell
> quarto add coatless-quarto/pyodide
> ```

It's working great! Thank you so much!
